---
kind: pipeline
name: housekeeping
type: docker
steps:
  - name: Lint
    image: osshelp/drone-linter
    settings:
      exclude_regex: "(inventory)"
      yml_files:
        - "ansible/*.yml"
        - "ansible/vars/*.yml"
        - "ansible/roles/*"
        - "drone/**/*.yml"
        - "github-action/*.yml"
      markdown_files:
        - "**/*.md"
        - "*.md"

trigger:
  branch:
    - dev
    - main
  event:
    - push
