---
name: housekeeping

on:
  push:
    branches:
      - main # branch to trigger workflow
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "**/*.md" # Linting all markdown files
